### PR TITLE
bucket-22

### PR DESCRIPTION
**Pull request by bobyuwono**

### CODE REVIEW

**Comment by tuanpalugada** [comment]
Ran Plan for dir: `frontend` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/bobyuwono_dev/.atlantis/repos/bobyuwono/terragrunt-gcp/4/default/frontend/default.tfplan\"" in "/home/bobyuwono_dev/.atlantis/repos/bobyuwono/terragrunt-gcp/4/default/frontend": exit status 1
╷
│ Error: Error acquiring the state lock
│ 
│ Error message: 2 errors occurred:
│ 	* writing "gs://terragrunting/frontend/terraform.tfstate/default.tflock"
│ failed: googleapi: Error 403: Access denied., forbidden
│ 	* storage: object doesn't exist
│ 
│ 
│ 
│ Terraform acquires a state lock to protect the state from being written
│ by multiple users at the same time. Please resolve the issue above and try
│ again. For most commands, you can disable locking with the "-lock=false"
│ flag, but this is not recommended.
╵

```
</details>

**Comment by bobyuwono** [comment]
atlantis plan -p terragrunt plan

**Comment by tuanpalugada** [comment]
```
Error: unknown argument(s) – plan.
Usage of plan:
  -d, --dir string         Which directory to run plan in relative to root of repo,
                           ex. 'child/dir'.
  -p, --project string     Which project to run plan for. Refers to the name of the
                           project configured in atlantis.yaml. Cannot be used at
                           same time as workspace or dir flags.
      --verbose            Append Atlantis log to comment.
  -w, --workspace string   Switch to this Terraform workspace before planning.
```

**Comment by bobyuwono** [comment]
atlantis plan -p terragrunt plan

**Comment by tuanpalugada** [comment]
```
Error: unknown argument(s) – plan.
Usage of plan:
  -d, --dir string         Which directory to run plan in relative to root of repo,
                           ex. 'child/dir'.
  -p, --project string     Which project to run plan for. Refers to the name of the
                           project configured in atlantis.yaml. Cannot be used at
                           same time as workspace or dir flags.
      --verbose            Append Atlantis log to comment.
  -w, --workspace string   Switch to this Terraform workspace before planning.
```

**Pull request closed without merging**
