### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by bobyuwono**

### CODE REVIEW

**Comment by tuanpalugada** [comment]
Ran Plan for dir: `frontend` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform init -input=false" in "/home/bobyuwono_dev/.atlantis/repos/bobyuwono/terragrunt-gcp/6/default/frontend": exit status 1

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of hashicorp/google from the dependency lock file
- Using hashicorp/google v4.0.0 from the shared cache directory
- Using hashicorp/random v3.4.3 from the shared cache directory
╷
│ Error: Failed to install provider from shared cache
│ 
│ Error while importing hashicorp/google v4.0.0 from the shared cache
│ directory: the provider cache at .terraform/providers has a copy of
│ registry.terraform.io/hashicorp/google 4.0.0 that doesn't match any of the
│ checksums recorded in the dependency lock file.
╵

╷
│ Error: Failed to install provider from shared cache
│ 
│ Error while importing hashicorp/random v3.4.3 from the shared cache
│ directory: the provider cache at .terraform/providers has a copy of
│ registry.terraform.io/hashicorp/random 3.4.3 that doesn't match any of the
│ checksums recorded in the dependency lock file.
╵


```
</details>

**Comment by bobyuwono** [comment]
atlantis -p terragrunt plan

**Comment by tuanpalugada** [comment]
```
Error: unknown command "-p".
Run 'atlantis --help' for usage.
```

**Comment by bobyuwono** [comment]
atlantis --help

**Comment by tuanpalugada** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan     Runs 'terraform plan' for the changes in this pull request.
           To plan a specific project, use the -d, -w and -p flags.
  apply    Runs 'terraform apply' on all unapplied plans from this pull request.
           To only apply a specific plan, use the -d, -w and -p flags.
  unlock   Removes all atlantis locks and discards all plans for this PR.
           To unlock a specific plan you can use the Atlantis UI.
  approve_policies
           Approves all current policy checking failures for the PR.
  version  Print the output of 'terraform version'
  help     View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Comment by bobyuwono** [comment]
terragrunt plan -p terra-frontend

**Comment by bobyuwono** [comment]
atlantis plan -p terra-frontend

**Comment by tuanpalugada** [comment]
**Plan Error**
```
cannot specify a project name unless an atlantis.yaml file exists to configure projects
```

**Pull request closed without merging**
